### ISSUE TITLE
Dashboard InfluxDB Internals: Datasource not found

### ISSUE THREAD

**Issue by fleimgruber** [tboggiano/grafana#1]
I wanted to try out the InfluxDB Internals dashboard. After import I get the error
```
Datasource named $InstanceStats was not found
```
multiple times. What am I missing?

**Comment by tboggiano** [comment]
Datasource is setup under Variables in Settings and has to match a pattern of /^$datasource-.*$/ so for example on my blog my data source is named InfluxDB-00-Internal.  I have new dashboard that needs to be uploaded due to Telegraf changing the names of the tables in one the newest versions so I'll that updated shortly as well.

**Comment by tboggiano** [comment]
@fleimgruber Were you able to get this to work?

**Comment by fleimgruber** [comment]
IIUC, you updated the dashboards since then. I will try with the newer ones and read the docs carefully. Will reopen if the problem persists.
